[package]
name = "stm32wb55-homekit"
version = "0.1.0"
authors = ["Dominik Boehi <dominik.boehi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stm32wb55 = { version = "*", path = "../stm32wb55" }
stm32wb-hal = { version = "0.1.1", path = "../stm32wb-hal" }
bluetooth-hci = { git = "https://github.com/danielgallagher0/bluetooth-hci" }


cortex-m = "0.6.2"
stm32wb-pac = "0.2"
as-slice = "0.1"
bit_field = "0.10.0"
heapless = "0.5.3"
nb = "0.1"
cortex-m-rtic = "0.5"
panic-halt = "0.2.0"
panic-reset = "0.1.0"
panic-semihosting = "0.5.0"
cortex-m-rt = "0.6.6"
usb-device = "0.2"
usbd-serial = "0.1.0"
# srp = { version = "*", path = "../rust_pakes/srp" }


[dependencies.embedded-hal]
version = "0.2.3"
features = ["unproven"]

[dependencies.byteorder]
version = "1"
default-features = false

[profile.release]
codegen-units = 1
debug = true
lto = true

[patch.crates-io]
num-bigint = { git = "https://github.com/rust-num/num-bigint.git" }