[default.general]
chip = "stm32wb55ccux"
log_level = "WARN"

#connect_under_reset = true

[default.flashing]
enabled = true

[default.rtt]
enabled = true
timeout = 20000
log_enabled = true

[default.probe]
speed = 1000

usb_vid = "1366"
usb_pid = "0101"
serial = "000801020506"


[log.flashing]
enabled = false

[log.rtt]
enabled = true
timeout = 20000
log_enabled = true

[log.probe]
speed = 4000

[log.reset]
enabled = true
