[default.general]
chip = "stm32wb55ccux"
log_level = "WARN"

[default.flashing]
enabled = "true"

[default.rtt]
enabled = "true"
timeout = 20000

[default.probe]
speed = 950


[log.rtt]
enabled = "true"
timeout = 20000

[log.probe]
speed = 950
