on:
  push:
    branches: [master]
  pull_request:

name: CI

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: thumbv7em-none-eabihf

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
